/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Code: typeof import('./src/components/code-generator/CodeGeneratorView.vue')['default']
    CodeGeneratorHeader: typeof import('./src/components/code-generator/layout/CodeGeneratorHeader.vue')['default']
    CodeGeneratorMain: typeof import('./src/components/code-generator/layout/CodeGeneratorMain.vue')['default']
    CodeGeneratorView: typeof import('./src/components/code-generator/CodeGeneratorView.vue')['default']
    CodePreview: typeof import('./src/components/code-generator/sections/preview-panel/CodePreview.vue')['default']
    ConfigPanel: typeof import('./src/components/code-generator/sections/config-panel/ConfigPanel.vue')['default']
    ConnectionPanel: typeof import('./src/components/code-generator/sections/connection-panel/ConnectionPanel.vue')['default']
    DatabaseLink: typeof import('./src/components/code-generator/main/databaseLink/DatabaseLink.vue')['default']
    DatabaseTypeSelect: typeof import('./src/components/code-generator/sections/connection-panel/DatabaseTypeSelect.vue')['default']
    DataTableStructure: typeof import('./src/components/code-generator/main/dataTableStructure/DataTableStructure.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    FileTabs: typeof import('./src/components/code-generator/sections/preview-panel/FileTabs.vue')['default']
    Footer: typeof import('./src/components/code-generator/footer/Footer.vue')['default']
    Header: typeof import('./src/components/code-generator/header/Header.vue')['default']
    Main: typeof import('./src/components/code-generator/main/Main.vue')['default']
    ParameterConfig: typeof import('./src/components/code-generator/main/parameterConfig/ParameterConfig.vue')['default']
    PreviewPanel: typeof import('./src/components/code-generator/sections/preview-panel/PreviewPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaSelect: typeof import('./src/components/code-generator/sections/structure-panel/SchemaSelect.vue')['default']
    StructurePanel: typeof import('./src/components/code-generator/sections/structure-panel/StructurePanel.vue')['default']
    TableSearch: typeof import('./src/components/code-generator/sections/structure-panel/TableSearch.vue')['default']
  }
}
