/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeGeneratorHeader: typeof import('./src/components/code-generator/layout/CodeGeneratorHeader.vue')['default']
    CodeGeneratorMain: typeof import('./src/components/code-generator/layout/CodeGeneratorMain.vue')['default']
    CodeGeneratorView: typeof import('./src/components/code-generator/CodeGeneratorView.vue')['default']
    CodePreview: typeof import('./src/components/code-generator/sections/preview-panel/CodePreview.vue')['default']
    ConfigPanel: typeof import('./src/components/code-generator/sections/config-panel/ConfigPanel.vue')['default']
    ConnectionPanel: typeof import('./src/components/code-generator/sections/connection-panel/ConnectionPanel.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FileTabs: typeof import('./src/components/code-generator/sections/preview-panel/FileTabs.vue')['default']
    PreviewPanel: typeof import('./src/components/code-generator/sections/preview-panel/PreviewPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StructurePanel: typeof import('./src/components/code-generator/sections/structure-panel/StructurePanel.vue')['default']
  }
}
